ALTER DATABASE itk SET timezone TO 'America/Vancouver';

CREATE TABLE IF NOT EXISTS Runs (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  end_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS RobinsTable (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  run_id INT REFERENCES Runs NOT NULL,
  length REAL,
  width REAL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
