ALTER DATABASE itk SET timezone TO 'America/Vancouver';

CREATE TABLE IF NOT EXISTS Runs (
  id INT PRIMARY KEY,
  module_id TEXT DEFAULT "prototype" NOT NULL,
  location TEXT DEFAULT "TRIUMF" NOT NULL,
  start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  end_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS IVCurve (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  run_id INT REFERENCES Runs NOT NULL,
  I REAL,
  V REAL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
);
